// <auto-generated />
using System;
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(BookingDBContext))]
    [Migration("20260708144525_AddXminConcurrencyToken")]
    partial class AddXminConcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.tbAppointmentStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Appointment_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Changed_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Changed_By_User_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("From_Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("To_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Appointment_Id");

                    b.HasIndex("Changed_By_User_Id");

                    b.ToTable("tbAppointment_Status_History");
                });

            modelBuilder.Entity("Data.Models.tbAppointments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Doctor_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Patient_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Slot_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Doctor_Id");

                    b.HasIndex("Patient_Id");

                    b.HasIndex("Slot_Id")
                        .IsUnique()
                        .HasDatabaseName("uq_active_appointment_per_slot")
                        .HasFilter("\"Status\" IN ('Reserved','Confirmed')");

                    b.ToTable("tbAppointments", t =>
                        {
                            t.HasCheckConstraint("CK_Appointments_Status", "\"Status\" IN ('Reserved','Confirmed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Data.Models.tbDoctors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone_Number")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tbDoctors");
                });

            modelBuilder.Entity("Data.Models.tbPatients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Date_Of_Birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone_Number")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tbPatients");
                });

            modelBuilder.Entity("Data.Models.tbSlots", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Doctor_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Start_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Doctor_Id", "Start_Time")
                        .IsUnique();

                    b.HasIndex("Doctor_Id", "Status", "Start_Time");

                    b.ToTable("tbSlots", t =>
                        {
                            t.HasCheckConstraint("CK_Slots_Status", "\"Status\" IN ('Available','Reserved','Confirmed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Data.Models.tbUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Doctor_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Refresh_Token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Refresh_Token_Expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Doctor_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tbUsers", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Admin','Doctor','Staff')");
                        });
                });

            modelBuilder.Entity("Data.Models.tbAppointmentStatusHistory", b =>
                {
                    b.HasOne("Data.Models.tbAppointments", "Appointment")
                        .WithMany("StatusHistory")
                        .HasForeignKey("Appointment_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.tbUsers", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("Changed_By_User_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("Data.Models.tbAppointments", b =>
                {
                    b.HasOne("Data.Models.tbDoctors", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("Doctor_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.tbPatients", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("Patient_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.tbSlots", "Slot")
                        .WithMany("Appointments")
                        .HasForeignKey("Slot_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Data.Models.tbSlots", b =>
                {
                    b.HasOne("Data.Models.tbDoctors", "Doctor")
                        .WithMany("Slots")
                        .HasForeignKey("Doctor_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Data.Models.tbUsers", b =>
                {
                    b.HasOne("Data.Models.tbDoctors", "Doctor")
                        .WithMany("Users")
                        .HasForeignKey("Doctor_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Data.Models.tbAppointments", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Data.Models.tbDoctors", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Slots");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Data.Models.tbPatients", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Data.Models.tbSlots", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
